import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_digest_email(
    gmail_user: str,
    gmail_app_password: str,
    recipient: str,
    funding_html: str,
    launches_html: str,
    site_url: str | None = None,
) -> None:
    today = datetime.now().strftime("%B %d, %Y")
    subject = f"Weekly Launch Digest — {today}"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f0f2f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;">
  <div style="max-width: 680px; margin: 0 auto; padding: 28px 16px;">

    <!-- Header -->
    <div style="background: #1a1a2e; border-radius: 8px 8px 0 0; padding: 28px 32px; margin-bottom: 0;">
      <h1 style="margin: 0 0 4px; font-size: 22px; font-weight: 700; color: #ffffff; letter-spacing: -0.3px;">Weekly Launch Digest</h1>
      <p style="margin: 0; color: #8888aa; font-size: 13px;">Week ending {today}</p>
      {f'<a href="{site_url}" style="display: inline-block; margin-top: 14px; background: #0055cc; color: white; font-size: 12px; font-weight: 600; padding: 7px 14px; border-radius: 5px; text-decoration: none;">Ask Claude follow-up questions &rarr;</a>' if site_url else ''}
    </div>

    <!-- Body -->
    <div style="background: white; border-radius: 0 0 8px 8px; padding: 32px; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">

      <!-- Funding section -->
      <div style="margin-bottom: 40px;">
        <div style="display: flex; align-items: center; margin-bottom: 20px;">
          <div style="width: 4px; height: 20px; background: #0055cc; border-radius: 2px; margin-right: 10px;"></div>
          <h2 style="margin: 0; font-size: 13px; font-weight: 700; color: #0055cc; text-transform: uppercase; letter-spacing: 1px;">VC Funding Announcements</h2>
        </div>
        {funding_html}
      </div>

      <!-- Launches section -->
      <div>
        <div style="display: flex; align-items: center; margin-bottom: 20px;">
          <div style="width: 4px; height: 20px; background: #007744; border-radius: 2px; margin-right: 10px;"></div>
          <h2 style="margin: 0; font-size: 13px; font-weight: 700; color: #007744; text-transform: uppercase; letter-spacing: 1px;">Top B2B Product Launches</h2>
        </div>
        {launches_html}
      </div>

    </div>

    <!-- Footer -->
    <p style="text-align: center; color: #aaa; font-size: 11px; margin: 16px 0 0;">
      Generated by Claude &middot; Automated weekly digest
    </p>

  </div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(gmail_user, gmail_app_password)
        server.send_message(msg)
